# Site settings
title: Mia Yu
SEOTitle: Mengya Yu's Blog
header-img: img/post-bg-universe.jpg
email: wenyuan@gmail.com
description: "个人博客，写点感想"
keyword: "编程，读书，旅游，摄影，萌宠"
url: "https://mengyayu.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     3153005112
zhihu_username:     暂无
github_username:    yomonah
# twitter_username:  
# facebook_username:  
# linkedin_username:  



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "享受每一刻，最美的时光"
sidebar-avatar: /img/head_pic.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "stack overflow",
        href: "http://stackoverflow.com/"
    },{
        title: "前端圈子",
        href: "http://www.whycss.com/"
    },{
        title: "前端外刊评论",
        href: "http://qianduan.guru/"
    },{
        title: "尤小石的博客",
        href: "http://blog.evanyou.me/"
    },{
        title: "阿里巴巴国际UED",
        href: "http://www.aliued.com/"
    },{
        title: "最牛前端",
        href: "http://f2er.club/"
    },{
        title: "A JS tip per day",
        href: "http://www.jstips.co/"
    },{
        title: "前端神盾局",
        href: "http://wepiaofei.github.io/blog/"
    }
]
